### ISSUE TITLE
Working out of IN versus abroad

### ISSUE THREAD

**Issue by namansancheti** [prateekbh/prateekbh#8]
Given your experience working out of both **IN + abroad** - curious to know, how do the two compare _in your opinion_ on:

a) Work + work related opportunities / events
b) Personal life
c) Pay / financial aspect
d) Any other aspect(s)

Thanks.

**Comment by prateekbh** [comment]
> a) Work + work related opportunities / events

Work totally depends on what are your focus areas, India has a lot of good product teams however when you look at infra teams the number of options gets a bit less.

Events in India are ample and of really high quality. So I don't really feel FOMO.

> b) Personal life

This makes me sad as most of the workplaces try to accommodate according to Eu or PST timezone. I feel its time that we realize that we're a team and both sides need to accommodate equally.

Also we have a culture of rewarding long hours at offices, night owls and midnight oil burners. While these are absolutely needed at certain times, for the rest they should be avoided. Leads and EMs need to actively discourage putting in 10-14 hours of a day into office work. Our work/projects might be called sprints but they're really a marathon. Lets not encourage behaviour that causes burnout.

c) Pay / financial aspect

This I feel is totally well taken care of in India. Indian salaries are upto the mark  at least in the bubble of companies I am working with.

d) Any other aspect(s)

**Comment by namansancheti** [comment]
Thanks a lot for sharing your thoughts - appreciate it 👍
